### ISSUE TITLE
Issue with downloading 'requirements.txt'

### ISSUE THREAD

**Issue by Ocean-Man1** [skd1993/instagram-saved-scraper#1]
Hello! First off love this idea and just in time for a project I've having trouble so I would love this library.
I'm getting this error whenever I install the `requirements.txt` where I cloned the repository. It's very strange.
Cheers.

`(venv) $ pip install -r requirements.txt
Collecting beautifulsoup4==4.9.3 (from -r requirements.txt (line 1))
  Downloading beautifulsoup4-4.9.3-py3-none-any.whl.metadata (4.2 kB)
Collecting black==21.12b0 (from -r requirements.txt (line 2))
  Downloading black-21.12b0-py3-none-any.whl.metadata (39 kB)
Collecting bs4==0.0.1 (from -r requirements.txt (line 3))
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting certifi==2021.5.30 (from -r requirements.txt (line 4))
  Downloading certifi-2021.5.30-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting cffi==1.14.6 (from -r requirements.txt (line 5))
  Downloading cffi-1.14.6.tar.gz (475 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.7/475.7 kB 15.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      Traceback (most recent call last):
        File "C:\$\pyprojs\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\$\pyprojs\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\$\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\$\AppData\Local\Temp\pip-build-env-yx5c8z6j\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\$\AppData\Local\Temp\pip-build-env-yx5c8z6j\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\$\AppData\Local\Temp\pip-build-env-yx5c8z6j\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\$\AppData\Local\Temp\pip-build-env-yx5c8z6j\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 127, in <module>
        File "<string>", line 105, in uses_msvc
        File "C:\$\AppData\Local\Temp\pip-build-env-yx5c8z6j\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 220, in try_compile
          self._compile(body, headers, include_dirs, lang)
        File "C:\$\AppData\Local\Temp\pip-build-env-yx5c8z6j\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 132, in _compile
          self.compiler.compile([src], include_dirs=include_dirs)
        File "C:\$\AppData\Local\Temp\pip-build-env-yx5c8z6j\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
          self.initialize()
        File "C:\$\AppData\Local\Temp\pip-build-env-yx5c8z6j\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\$\AppData\Local\Temp\pip-build-env-yx5c8z6j\overlay\Lib\site-packages\setuptools\msvc.py", line 232, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\$\AppData\Local\Temp\pip-build-env-yx5c8z6j\overlay\Lib\site-packages\setuptools\msvc.py", line 189, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError("Unable to find vcvarsall.bat")
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.`

**Comment by fahmmin** [comment]
same here , got any solutions?

**Comment by Fecsio** [comment]
You need to install Microsoft C++ Build Tools as stated in the error trace.
